[package]
name = "multi_sig"  

version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
borsh = "1.5.1"
log = "0.4.22"
serde = "1.0.213"
solana-program = "2.0.14"
thiserror = "1.0.65"

[lib]
crate-type = ["cdylib", "lib"]